### ISSUE TITLE
how to show as widget

### ISSUE THREAD

**Issue by SamadDev** [taufiqjack/hijriyah_indonesia#3]
well done you have done a nice job but is there any way to show it as a widget?

**Comment by taufiqjack** [comment]
in documentation already for showing.

you call :
Text("${Hijriyah.fromDate(DateTime.parse(dateTime.toString()).toLocal()).toFormat("dd MMMM yyyy"}");

**Comment by SamadDev** [comment]
I mean to shwo as widget(date time picker)

**Comment by taufiqjack** [comment]
you also using flutter_localizations packages for change arabic format

**Comment by SamadDev** [comment]
Yeas even i have used that
