### ISSUE TITLE
Typo Hari Jumat

### ISSUE THREAD

**Issue by n2ng-dev** [taufiqjack/hijriyah_indonesia#4]
Penulisan hari Jumat ada kesalahan jadi "Ju2at", untuk hari yg lain sudah sesuai

Thanks

![Screenshot_20240816_232025.jpg](https://github.com/user-attachments/assets/84ca7edb-b587-4eac-9978-a1d0be63d958)

**Comment by taufiqjack** [comment]
Please update to version 0.1.5
https://github.com/taufiqjack/hijriyah_indonesia
