### ISSUE TITLE
Set locale English & Indonesia 

### ISSUE THREAD

**Issue by n2ng-dev** [taufiqjack/hijriyah_indonesia#5]
Request set local Indonesia & English for better language translation

**Comment by taufiqjack** [comment]
please add -> Hijriyah.setLocal(locale);
in
 void Main() {
  Hijriyah.setLocal('id');
  English is default or empty
}

**Comment by n2ng-dev** [comment]
Days name still typo

Locale 'en'
fullDate()
![Screenshot_20240824_214602.jpg](https://github.com/user-attachments/assets/3e550480-7c28-4b1d-963a-ff6c89b080b3)

Locale 'id'
fullDate()
![Screenshot_20240824_214636.jpg](https://github.com/user-attachments/assets/88212fae-9b75-42f2-bcac-5efd58b41239)

**Comment by taufiqjack** [comment]
Done,
please update version package to 0.1.5
